### ISSUE TITLE
pip reports package version as 0.0.0

### ISSUE THREAD

**Issue by dstansby** [conda-forge/cellfinder-core-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=707010&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=652

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by willGraham01** [comment]
Fixed by #12: as @dstansby suspected, it was `setuptools_scm` missing from the `host` field in the recipe. 

https://github.com/brainglobe/cellfinder-core/issues/179
