### ISSUE TITLE
[BUG?] Versions >=0.4.0 cannot be installed using only conda-forge channels

### ISSUE THREAD

**Issue by willGraham01** [conda-forge/cellfinder-core-feedstock#13]
### Comment:

Version `>=0.4.0` is noarch, and depends on tensorflow `>=2.5.0`. 

However, [only version 1.14.0 of tensorflow](https://anaconda.org/conda-forge/tensorflow) is available via conda-forge for Windows OSs (this appears to conflict with the [claims of the tensorflow-feedstock badges though](https://github.com/conda-forge/tensorflow-feedstock), but conda cannot locate any versions on Windows above 1.14.0).

This means that any packages to be uploaded to conda-forge that require cellfinder-core >=0.4.0 [have unresolvable dependencies on Windows](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=732367&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=2fb5b0a7-737c-5f5c-8f3f-f6db6174bacf&l=357).

**Workarounds**
For conda-forge recipes: forcing Windows to use cellfinder-core<0.4.0 will bypass the issue but leave the user with a broken package, unless they follow the step below to install a compatible version of tensorflow first. This also makes any recipes illegible for noarch.

A compatible version of tensorflow can be installed via pip on Windows, so it is possible to install cellfinder-core>=0.4.0 manually by:
- `pip install tensorflow`
- `conda install cellfinder-core>=0.4.0`

But of course, conda-forge recipes cannot use non-conda channels, so this is not available when uploading new recipes to `staged-recipes`.

**Comment by adamltyson** [comment]
Based on [this page](https://www.tensorflow.org/install/pip#windows-native) it looks like TensorFlow is kinda no-longer supported on Windows (at least using a GPU). Can we specify the cpu version for Windows (and is that available?).

**Comment by willGraham01** [comment]
It's more the fact that we can't install any tensorflow version above 2.0.0 using only conda channels on Windows, and cellfinder-core requires at least v2.5.0. In turn, it means that anything that depends on cellfinder-core>=0.4.0 can't be conda-installed on Windows, since conda installs can only use conda channels to fetch dependencies.

There's [this hack that I've employed for the meta-package](https://github.com/conda-forge/staged-recipes/pull/23136/commits/38cec9e81ca9a0fedd249e2bbde3f72801862e07) that seems to work since, cellfinder-core v3.1.0 didn't actually install tensorflow, so conda can resolve the dependencies. Then the manual pip-install trick I described can be done by users manually to get it to work.

**Comment by hmaarrfk** [comment]
Anything that has a hard dependency on tensorflow cannot be installed using only `conda-forge`.

To fix this, we need to build tesnsorflow at conda-forge, but this isn't really easy.

PRs welcome at the tensorflow feedstock.

**Comment by adamltyson** [comment]
@willGraham01 I think we can make TF optional for now. It will also make downloads much quicker for most users (TF is only used for cellfinder).

**Comment by willGraham01** [comment]
> I think we can make TF optional for now. It will also make downloads much quicker for most users (TF is only used for cellfinder).

Conda-forge doesn't allow optional dependencies - TF is either in or out. 

I can make another package like `cellfinder-core-no-TF` and upload that to the forge if we want? **BUT** TF is also a hard dependency of the underlying `cellfinder-core` `PyPI` package, so we'd be allowing users to install a broken package into their environment if they're not careful. And we'd be unable to run any kind of tests in the corresponding recipe since they'd all fail at the import / pip check step.

**Comment by adamltyson** [comment]
> We modify the cellfinder-core pypi package to have an optional tensorflow dependency; cellfinder-core[tensorflow], and then make the conda package the one that only installs the base package? Although in doing that we'd also need to update cellfinder-napari and cellfinder's package info too.

I think this is probably the best. None of the options seem particularly satisfactory though!

**Comment by willGraham01** [comment]
> I think this is probably the best. None of the options seem particularly satisfactory though!

Sadly the real blocker appears to be conda-forge itself. Everything we have is completely fine if `pip install` is used instead.

Am going to move/link this issue onto [`brainglobe/BrainGlobe`](https://github.com/brainglobe/BrainGlobe) so that all the required changes are recorded in one place, then will get started on the necessary changes :+1:

**Comment by dstansby** [comment]
What about reverting back from being a `noarch` package to just uploading packages for Linux and macOS? In retrospect I think this is what I should have done when I released version 0.4.0.

**Comment by adamltyson** [comment]
Would that make all the upstream dependencies linux and macOS only though?

**Comment by dstansby** [comment]
You could specify platform-dependent dependencies in dependent packages, e.g. in a brainglobe meta package you could specify something like ` - cellfinder-core # [not win]`

**Comment by willGraham01** [comment]
I guess that also leaves certain users (potentially unknowingly) without some `BrainGlobe` tools after installing the meta-package - [also relevant is Adam's comment here.](https://github.com/brainglobe/BrainGlobe/issues/27#issuecomment-1617817657)

I guess it's which evil do you want:
- `conda`-installing doesn't fetch all the tools, but the ones you get all work.
- `conda`-installing fetches all the tools, but some are broken until you manually install something else.

**Comment by adamltyson** [comment]
> conda-installing fetches all the tools, but some are broken until you manually install something else.

This gets my vote. Most users will be using BrainGlobe tools via napari plugins, so this would mean the tools are visible, and we can provide explicit instructions on how to get them working.

**Comment by hmaarrfk** [comment]
You may want to consider `noarch_paltforms` to have the best of both world:
https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-packages-with-os-specific-dependencies

Discussion here:
https://github.com/conda-forge/conda-forge.github.io/issues/1840

**Comment by willGraham01** [comment]
Thanks for the suggestion Mark! 

`noarch_platforms` look to resolve our problems here (see #14) and address some of our `tensorflow` woes at the same time. 

With #14, `cellfinder-core` is still be un-`import`able on Windows due to missing `tensorflow`, but we're already prepared to acknowledge this:
- https://github.com/brainglobe/cellfinder-core/pull/186, introduced changes to guard against this possibility anyway.
- https://github.com/brainglobe/cellfinder-core/pull/191, we can alert Windows users trying to install via `conda` to this problem.

So with these changes to `cellfinder-core`, and new PyPI upload, #14 will close this issue, albeit with the Windows caveat.
